export const dict = {
  "zh": {
    "appName": "KiboTalk",
    "conversation": "对话",
    "suggestions": "回复建议",
    "conversationHistory": "对话记录",
    "history": "历史会话",
    "settings": "设置",
    "close": "关闭",
    "back": "返回",
    "start": "开始新会话",
    "pause": "暂停",
    "resume": "继续",
    "stop": "停止",
    "stopAndSave": "停止并保存",
    "cancel": "取消",
    "confirm": "确认",
    "listening": "正在转写",
    "paused": "已暂停",
    "stopped": "已停止",
    "preparing": "正在准备语音能力…",
    "preparationFailed": "语音能力准备失败",
    "emptySuggestions": "开始说话后，回复建议会出现在这里",
    "generatingSuggestions": "正在生成建议…",
    "aiConnecting": "正在连接模型…",
    "aiRetrying": "正在重新生成（保留原上下文）…",
    "aiAttempt": "第 {n} 次重试",
    "aiStreaming": "正在流式生成…",
    "aiDone": "生成完成",
    "aiFailed": "生成失败",
    "aiRetry": "重试",
    "previousRound": "上一轮",
    "noTranscript": "还没有对话内容",
    "me": "我",
    "other": "对方",
    "sttFailed": "这段转写失败",
    "aiSuggestions": "AI 建议",
    "stopTitle": "停止并保存这次会话？",
    "stopDescription": "当前转写和建议会立即保存。再次开启时会创建新的对话场景。",
    "quit": "退出 KiboTalk",
    "quitTitleActive": "结束会话并退出？",
    "quitTitleStopped": "退出 KiboTalk？",
    "quitDescriptionActive": "会话会先封存并保存，然后退出 KiboTalk。",
    "quitDescriptionStopped": "悬浮窗和状态栏图标都会关闭。",
    "general": "通用",
    "uiLanguage": "界面语言",
    "uiLanguageDescription": "停止会话后可切换；修改后立即生效。",
    "theme": "外观",
    "system": "跟随系统",
    "light": "浅色",
    "dark": "深色",
    "launchAtLogin": "登录时启动",
    "conversationSettings": "对话",
    "conversationLanguage": "对话语言",
    "level": "当前水平",
    "audioSource": "音频来源",
    "microphone": "麦克风",
    "systemAudio": "系统音频",
    "bothAudio": "两者都要",
    "microphoneDescription": "现场对话、面对面聊天",
    "systemAudioDescription": "线上通话、看视频/播客",
    "bothAudioDescription": "同时采集你和屏幕里的声音",
    "microphoneDevice": "麦克风设备",
    "systemDefault": "系统默认",
    "headphonesHint": "同时采集时建议佩戴耳机，避免扬声器回声。",
    "voiceprint": "声纹",
    "voiceprintReady": "已录入",
    "voiceprintMissing": "未录入",
    "voiceprintFailed": "声纹录入失败，请检查麦克风权限后重试。",
    "voiceprintTooQuiet": "没有检测到足够清晰的语音，请靠近麦克风并在安静环境中重录。",
    "voiceprintTooShort": "录音太短，请完整朗读屏幕上的三句话后再结束。",
    "rerecordVoiceprint": "重新录制声纹",
    "deleteVoiceprint": "删除声纹",
    "deleteVoiceprintTitle": "删除声纹？",
    "deleteVoiceprintDescription": "删除后需要重新录入，才能开始新会话。历史记录不会被删除。",
    "permissions": "权限",
    "microphonePermission": "麦克风权限",
    "screenPermission": "系统音频 / 屏幕录制权限",
    "granted": "已允许",
    "needsPermission": "需要允许",
    "requestPermission": "请求权限",
    "openSystemSettings": "打开系统设置",
    "dataPrivacy": "数据与隐私",
    "clearHistory": "清除历史记录",
    "clearHistoryTitle": "清除全部历史记录？",
    "clearHistoryDescription": "已停止的会话、转写、建议与总结将从本机永久删除。",
    "deleteSession": "删除这条记录",
    "deleteSessionTitle": "删除这条会话记录？",
    "deleteSessionDescription": "该会话的转写、建议与总结将被永久删除，无法恢复。",
    "resetPersonalData": "清除个人数据并重置",
    "resetTitle": "清除个人数据并重置？",
    "resetDescription": "会删除偏好、声纹和历史，但保留已经准备好的本机语音能力。",
    "about": "关于",
    "version": "版本",
    "lockedWhileActive": "进行中或暂停的会话会锁定会话设置。停止后即可修改。",
    "currentSession": "本次会话",
    "noHistory": "还没有已保存的会话",
    "summaryPending": "正在整理本次会话…",
    "summaryFailed": "整理失败",
    "retry": "重试",
    "syncPending": "待同步",
    "activeSessionRecovered": "上次会话意外中断，已恢复为暂停状态。",
    "selectLanguage": "选择对话语言",
    "onboardingDescription": "确认双方使用的语言和你的当前水平。",
    "continueVoiceprint": "确认并继续",
    "languageJapanese": "日语",
    "languageEnglish": "英语",
    "languageChinese": "中文",
    "levelBeginner": "初级",
    "levelIntermediate": "中级",
    "levelAdvanced": "高级",
    "more": "更多操作",
    "showWindow": "显示悬浮窗",
    "hideWindow": "隐藏悬浮窗",
    "moveWindow": "移动悬浮窗",
    "stepIntro": "说明",
    "stepRecord": "录入",
    "stepDone": "完成",
    "recordVoiceTitle": "录一下声音",
    "recordVoiceDescription": "读一段短口令，让 KiboTalk 分清哪句是你说的。大约 15 秒，只保存在这台设备上。",
    "startRecording": "开始录音",
    "preparingSpeech": "正在准备语音能力…",
    "pleaseRead": "请朗读：",
    "stopRecording": "结束录音",
    "retryRecording": "重试录音",
    "preparingMicrophone": "正在准备麦克风…",
    "processing": "处理中…",
    "voiceprintSaved": "声纹已保存",
    "voiceprintSavedDescription": "这台设备已经能认出你的声音了，可以开始真实会话，系统会自动分清谁在说话。",
    "enterSession": "进入会话",
    "rerecord": "重新录制",
    "noAudioRecorded": "没有录到音频，请重试",
    "voiceprintSavedLocal": "声纹已保存到本机",
    "errorPrefix": "错误：",
    "sessionSummary": "会话总结",
    "sessionDetails": "会话详情",
    "voiceprintRequired": "请先在设置中录入声纹，再开始会话。",
    "sessionUnavailable": "语音暂时不可用，请检查权限或音频设置后重试。",
    "selectNetworkNode": "选择本次会话的网络节点",
    "networkNodeDescription": "以下延迟为你的设备到节点的实测往返时间。选择后，本次会话中不会切换节点。",
    "checkingLatency": "正在测量节点延迟…",
    "localNode": "本地节点",
    "japanNode": "日本主节点",
    "relayNode": "中转节点",
    "encryptedConnection": "HTTPS 加密连接",
    "insecureRelayWarning": "HTTP 未加密：语音、提示词、回复和短令牌可能被链路中间方看到或篡改。选择即表示你了解此风险。",
    "nodeUnreachable": "当前不可达",
    "nodeProbeFailed": "节点测速失败",
    "refreshLatency": "重新测速",
    "defaultNode": "设置默认",
    "defaultNetworkNode": "默认网络节点",
    "defaultNetworkNodeDescription": "停止会话后可修改；下一次会话开始时仍会显示最新延迟并请你确认。"
  },
  "ja": {
    "appName": "KiboTalk",
    "conversation": "会話",
    "suggestions": "返信候補",
    "conversationHistory": "会話ログ",
    "history": "履歴",
    "settings": "設定",
    "close": "閉じる",
    "back": "戻る",
    "start": "新しい会話を開始",
    "pause": "一時停止",
    "resume": "再開",
    "stop": "停止",
    "stopAndSave": "停止して保存",
    "cancel": "キャンセル",
    "confirm": "確認",
    "listening": "文字起こし中",
    "paused": "一時停止中",
    "stopped": "停止済み",
    "preparing": "音声機能を準備中…",
    "preparationFailed": "音声機能を準備できませんでした",
    "emptySuggestions": "話し始めると、ここに返信候補が表示されます",
    "generatingSuggestions": "返信候補を作成中…",
    "aiConnecting": "モデルに接続中…",
    "aiRetrying": "同じ文脈で再生成中…",
    "aiAttempt": "リトライ {n} 回目",
    "aiStreaming": "ストリーミング生成中…",
    "aiDone": "生成完了",
    "aiFailed": "生成に失敗しました",
    "aiRetry": "再試行",
    "previousRound": "前のターン",
    "noTranscript": "会話はまだありません",
    "me": "自分",
    "other": "相手",
    "sttFailed": "この部分の文字起こしに失敗しました",
    "aiSuggestions": "AI 候補",
    "stopTitle": "この会話を停止して保存しますか？",
    "stopDescription": "文字起こしと候補を保存します。次に開始すると新しい会話になります。",
    "quit": "KiboTalk を終了",
    "quitTitleActive": "会話を終了してアプリを終了しますか？",
    "quitTitleStopped": "KiboTalk を終了しますか？",
    "quitDescriptionActive": "会話を保存してから KiboTalk を終了します。",
    "quitDescriptionStopped": "フローティングウィンドウとメニューバーアイコンを閉じます。",
    "general": "一般",
    "uiLanguage": "表示言語",
    "uiLanguageDescription": "会話停止中のみ変更できます。すぐに反映されます。",
    "theme": "外観",
    "system": "システム",
    "light": "ライト",
    "dark": "ダーク",
    "launchAtLogin": "ログイン時に起動",
    "conversationSettings": "会話",
    "conversationLanguage": "会話言語",
    "level": "現在のレベル",
    "audioSource": "音声ソース",
    "microphone": "マイク",
    "systemAudio": "システム音声",
    "bothAudio": "両方",
    "microphoneDescription": "対面会話、身近な話",
    "systemAudioDescription": "オンライン通話・動画音声",
    "bothAudioDescription": "自分と相手の声を同時に収録",
    "microphoneDevice": "マイクデバイス",
    "systemDefault": "システム既定",
    "headphonesHint": "同時収録では、スピーカーの回り込みを防ぐためヘッドホンを推奨します。",
    "voiceprint": "声紋",
    "voiceprintReady": "登録済み",
    "voiceprintMissing": "未登録",
    "voiceprintFailed": "声紋を登録できませんでした。マイク権限を確認して、もう一度お試しください。",
    "voiceprintTooQuiet": "はっきりした音声を検出できませんでした。マイクに近づき、静かな場所でもう一度録音してください。",
    "voiceprintTooShort": "録音が短すぎます。画面の3文を最後まで読んでから終了してください。",
    "rerecordVoiceprint": "声紋を再登録",
    "deleteVoiceprint": "声紋を削除",
    "deleteVoiceprintTitle": "声紋を削除しますか？",
    "deleteVoiceprintDescription": "新しい会話を始めるには再登録が必要です。履歴は削除されません。",
    "permissions": "権限",
    "microphonePermission": "マイク権限",
    "screenPermission": "システム音声 / 画面収録権限",
    "granted": "許可済み",
    "needsPermission": "許可が必要",
    "requestPermission": "権限をリクエスト",
    "openSystemSettings": "システム設定を開く",
    "dataPrivacy": "データとプライバシー",
    "clearHistory": "履歴を消去",
    "clearHistoryTitle": "すべての履歴を消去しますか？",
    "clearHistoryDescription": "停止済みの会話、文字起こし、候補、まとめをこの端末から削除します。",
    "deleteSession": "この記録を削除",
    "deleteSessionTitle": "この会話記録を削除しますか？",
    "deleteSessionDescription": "この会話の文字起こし・候補・まとめが完全に削除され、元に戻せません。",
    "resetPersonalData": "個人データを消去してリセット",
    "resetTitle": "個人データを消去してリセットしますか？",
    "resetDescription": "設定、声紋、履歴を削除します。準備済みの音声機能は残ります。",
    "about": "このアプリについて",
    "version": "バージョン",
    "lockedWhileActive": "進行中または一時停止中は会話設定を変更できません。停止後に変更できます。",
    "currentSession": "今回の会話",
    "noHistory": "保存された会話はまだありません",
    "summaryPending": "会話を整理しています…",
    "summaryFailed": "整理に失敗しました",
    "retry": "再試行",
    "syncPending": "同期待ち",
    "activeSessionRecovered": "前回の会話が中断されたため、一時停止状態で復元しました。",
    "selectLanguage": "会話言語を選択",
    "onboardingDescription": "二人が使う言語と、あなたの現在のレベルを選んでください。",
    "continueVoiceprint": "確認して続ける",
    "languageJapanese": "日本語",
    "languageEnglish": "英語",
    "languageChinese": "中国語",
    "levelBeginner": "初級",
    "levelIntermediate": "中級",
    "levelAdvanced": "上級",
    "more": "その他",
    "showWindow": "ウィンドウを表示",
    "hideWindow": "ウィンドウを隠す",
    "moveWindow": "ウィンドウを移動",
    "stepIntro": "説明",
    "stepRecord": "登録",
    "stepDone": "完了",
    "recordVoiceTitle": "声を登録",
    "recordVoiceDescription": "短いフレーズを読み、あなたの発話を識別できるようにします。約15秒で、この端末だけに保存されます。",
    "startRecording": "録音を開始",
    "preparingSpeech": "音声機能を準備中…",
    "pleaseRead": "読み上げてください：",
    "stopRecording": "録音を終了",
    "retryRecording": "録音をやり直す",
    "preparingMicrophone": "マイクを準備中…",
    "processing": "処理中…",
    "voiceprintSaved": "声紋を保存しました",
    "voiceprintSavedDescription": "この端末であなたの声を識別できるようになりました。実際の会話を始められます。",
    "enterSession": "会話を開始",
    "rerecord": "再登録",
    "noAudioRecorded": "音声を録音できませんでした。もう一度お試しください",
    "voiceprintSavedLocal": "声紋をこの端末に保存しました",
    "errorPrefix": "エラー：",
    "sessionSummary": "会話のまとめ",
    "sessionDetails": "会話の詳細",
    "voiceprintRequired": "会話を始める前に、設定で声紋を登録してください。",
    "sessionUnavailable": "音声を利用できません。権限または音声設定を確認して、もう一度お試しください。",
    "selectNetworkNode": "このセッションのネットワークノードを選択",
    "networkNodeDescription": "表示される遅延は、この端末から各ノードまでの実測往復時間です。セッション中はノードを切り替えません。",
    "checkingLatency": "ノードの遅延を測定しています…",
    "localNode": "ローカルノード",
    "japanNode": "日本メインノード",
    "relayNode": "リレーノード",
    "encryptedConnection": "HTTPS 暗号化接続",
    "insecureRelayWarning": "HTTP は暗号化されません。音声、プロンプト、返信、短期トークンを経路上の第三者が閲覧または改ざんする可能性があります。選択すると、このリスクを理解したものとみなされます。",
    "nodeUnreachable": "現在接続できません",
    "nodeProbeFailed": "ノードの測定に失敗しました",
    "refreshLatency": "再測定",
    "defaultNode": "設定の既定",
    "defaultNetworkNode": "既定のネットワークノード",
    "defaultNetworkNodeDescription": "会話停止中に変更できます。次の開始時にも最新の遅延を表示して確認します。"
  },
  "en": {
    "appName": "KiboTalk",
    "conversation": "Conversation",
    "suggestions": "Reply suggestions",
    "conversationHistory": "Transcript",
    "history": "History",
    "settings": "Settings",
    "close": "Close",
    "back": "Back",
    "start": "Start new session",
    "pause": "Pause",
    "resume": "Resume",
    "stop": "Stop",
    "stopAndSave": "Stop and save",
    "cancel": "Cancel",
    "confirm": "Confirm",
    "listening": "Transcribing",
    "paused": "Paused",
    "stopped": "Stopped",
    "preparing": "Preparing speech features…",
    "preparationFailed": "Could not prepare speech features",
    "emptySuggestions": "Start speaking and reply suggestions will appear here",
    "generatingSuggestions": "Generating suggestions…",
    "aiConnecting": "Connecting to the model…",
    "aiRetrying": "Retrying with the same context…",
    "aiAttempt": "Attempt {n}",
    "aiStreaming": "Streaming response…",
    "aiDone": "Response complete",
    "aiFailed": "Generation failed",
    "aiRetry": "Retry",
    "previousRound": "Previous turn",
    "noTranscript": "No conversation yet",
    "me": "Me",
    "other": "Other",
    "sttFailed": "Transcription failed for this segment",
    "aiSuggestions": "AI suggestions",
    "stopTitle": "Stop and save this session?",
    "stopDescription": "The transcript and suggestions will be saved now. Starting again creates a new conversation.",
    "quit": "Quit KiboTalk",
    "quitTitleActive": "End the session and quit?",
    "quitTitleStopped": "Quit KiboTalk?",
    "quitDescriptionActive": "The session will be sealed and saved before KiboTalk quits.",
    "quitDescriptionStopped": "The floating window and menu bar icon will close.",
    "general": "General",
    "uiLanguage": "Interface language",
    "uiLanguageDescription": "Change it only while stopped. The interface updates immediately.",
    "theme": "Appearance",
    "system": "System",
    "light": "Light",
    "dark": "Dark",
    "launchAtLogin": "Launch at login",
    "conversationSettings": "Conversation",
    "conversationLanguage": "Conversation language",
    "level": "Current level",
    "audioSource": "Audio source",
    "microphone": "Microphone",
    "systemAudio": "System audio",
    "bothAudio": "Both",
    "microphoneDescription": "In-person conversation",
    "systemAudioDescription": "Online calls or media audio",
    "bothAudioDescription": "Capture both sides at once",
    "microphoneDevice": "Microphone device",
    "systemDefault": "System default",
    "headphonesHint": "Use headphones when capturing both sources to prevent speaker echo.",
    "captureMode": "Input mode",
    "captureModeDescription": "Choose how the app knows a turn is finished.",
    "pushMode": "Hold to talk",
    "pushModeDescription": "Hold a button while someone speaks; ideas start when you release.",
    "continuousMode": "Always listening",
    "continuousModeDescription": "Keeps transcribing; tap for ideas whenever you want them.",
    "holdMe": "Hold: me",
    "holdOther": "Hold: other",
    "holdHint": "Hold while the person speaks, release to finish the sentence.",
    "askIdeas": "Give me ideas",
    "permissions": "Permissions",
    "microphonePermission": "Microphone permission",
    "screenPermission": "System audio / screen recording permission",
    "granted": "Allowed",
    "needsPermission": "Permission needed",
    "requestPermission": "Request permission",
    "openSystemSettings": "Open system settings",
    "dataPrivacy": "Data & privacy",
    "clearHistory": "Clear history",
    "clearHistoryTitle": "Clear all history?",
    "clearHistoryDescription": "Stopped sessions, transcripts, suggestions, and summaries will be deleted from this device.",
    "deleteSession": "Delete this session",
    "deleteSessionTitle": "Delete this session?",
    "deleteSessionDescription": "This session's transcript, suggestions, and summary will be permanently deleted.",
    "resetPersonalData": "Clear personal data and reset",
    "resetTitle": "Clear personal data and reset?",
    "resetDescription": "Preferences and history are deleted. Prepared speech features remain.",
    "about": "About",
    "version": "Version",
    "lockedWhileActive": "Conversation settings are locked while running or paused. Stop the session to change them.",
    "currentSession": "Current session",
    "noHistory": "No saved sessions yet",
    "summaryPending": "Organizing this session…",
    "summaryFailed": "Could not organize this session",
    "retry": "Retry",
    "syncPending": "Sync pending",
    "activeSessionRecovered": "The previous session was interrupted and restored as paused.",
    "selectLanguage": "Choose conversation language",
    "onboardingDescription": "Confirm the language both people will use and your current level.",
    "continueSetup": "Confirm and continue",
    "languageJapanese": "Japanese",
    "languageEnglish": "English",
    "languageChinese": "Chinese",
    "levelBeginner": "Beginner",
    "levelIntermediate": "Intermediate",
    "levelAdvanced": "Advanced",
    "more": "More actions",
    "showWindow": "Show floating window",
    "hideWindow": "Hide floating window",
    "moveWindow": "Move floating window",
    "processing": "Processing…",
    "errorPrefix": "Error:",
    "sessionSummary": "Session summary",
    "sessionDetails": "Session details",
    
    "sessionUnavailable": "Speech is unavailable. Check permissions or audio settings and try again.",
    "selectNetworkNode": "Choose a network node for this session",
    "networkNodeDescription": "Latency is the measured round trip from this device to each node. The node will not change during the session.",
    "checkingLatency": "Measuring node latency…",
    "localNode": "Local node",
    "japanNode": "Japan primary",
    "relayNode": "Relay node",
    "encryptedConnection": "Encrypted with HTTPS",
    "insecureRelayWarning": "HTTP is not encrypted. An intermediary may read or alter audio, prompts, replies, and the short-lived token. Selecting it confirms you understand this risk.",
    "nodeUnreachable": "Currently unreachable",
    "nodeProbeFailed": "Could not measure node latency",
    "refreshLatency": "Measure again",
    "defaultNode": "Settings default",
    "defaultNetworkNode": "Default network node",
    "defaultNetworkNodeDescription": "Change it while stopped. The next session still shows fresh latency and asks for confirmation."
  }
} as const;

export type UiLang = keyof typeof dict;
export type TKey = keyof (typeof dict)["en"];
