export const dict = {
  zh: {
    appName: "KiboTalk",
    conversation: "对话",
    suggestions: "回复建议",
    conversationHistory: "对话记录",
    history: "历史会话",
    settings: "设置",
    close: "关闭",
    back: "返回",
    start: "开始新会话",
    pause: "暂停",
    resume: "继续",
    stop: "停止",
    stopAndSave: "停止并保存",
    cancel: "取消",
    confirm: "确认",
    listening: "正在转写",
    paused: "已暂停",
    stopped: "已停止",
    preparing: "正在准备语音能力…",
    preparationFailed: "语音能力准备失败",
    emptySuggestions: "点「开始」后，三条可直接说出口的回复会出现在这里",
    generatingSuggestions: "正在生成建议…",
    aiConnecting: "正在连接模型…",
    aiRetrying: "正在重新生成（保留原上下文）…",
    aiAttempt: "第 {n} 次重试",
    aiStreaming: "正在流式生成…",
    aiDone: "生成完成",
    aiFailed: "生成失败",
    aiRetry: "重试",
    previousRound: "上一轮",
    noTranscript: "还没有对话内容",
    me: "我",
    other: "对方",
    sttFailed: "这段转写失败",
    aiSuggestions: "AI 建议",
    stopTitle: "停止并保存这次会话？",
    stopDescription: "当前转写和建议会立即保存。再次开启时会创建新的对话场景。",
    quit: "退出 KiboTalk",
    quitTitleActive: "结束会话并退出？",
    quitTitleStopped: "退出 KiboTalk？",
    quitDescriptionActive: "会话会先封存并保存，然后退出 KiboTalk。",
    quitDescriptionStopped: "悬浮窗和状态栏图标都会关闭。",
    general: "通用",
    uiLanguage: "界面语言",
    uiLanguageDescription: "停止会话后可切换；修改后立即生效。",
    theme: "外观",
    system: "跟随系统",
    light: "浅色",
    dark: "深色",
    launchAtLogin: "登录时启动",
    conversationSettings: "对话",
    conversationLanguage: "对话语言",
    level: "当前水平",
    audioSource: "音频来源",
    microphone: "麦克风",
    systemAudio: "系统音频",
    bothAudio: "两者都要",
    microphoneDescription: "现场对话、面对面聊天",
    systemAudioDescription: "线上通话、看视频/播客",
    bothAudioDescription: "同时采集你和屏幕里的声音",
    microphoneDevice: "麦克风设备",
    systemDefault: "系统默认",
    headphonesHint: "同时采集时建议佩戴耳机，避免扬声器回声。",
    captureMode: "输入方式",
    captureModeDescription: "选择系统如何判断一句话说完了。",
    pushMode: "按住说话",
    pushModeDescription: "谁在说话就按住谁的按钮，松手立刻生成思路。",
    continuousMode: "持续聆听",
    continuousModeDescription: "一直转写；可在设置里开关「自动出思路」。",
    panelLayout: "面板排列",
    panelLayoutDescription: "选择对话框与回复建议的排列方式。",
    layoutAuto: "自动",
    layoutAutoDescription: "电脑左右并排，手机上下堆叠",
    layoutRow: "横向",
    layoutRowDescription: "始终左右并排显示两个框",
    layoutColumn: "纵向",
    layoutColumnDescription: "始终上下排列，两个框都限高",
    scrollSync: "滚动方式",
    scrollSyncDescription: "左右两栏是否跟随彼此滚动。",
    scrollLinked: "联动滚动",
    scrollLinkedDescription: "滚动一栏时另一栏按比例跟随",
    scrollIndependent: "独立滚动",
    scrollIndependentDescription: "两栏各自滚动，互不打断",
    mobileDock: "手机按钮样式",
    mobileDockDescription: "调整底部“按住说话”区域，避免遮挡上方内容。",
    dockFloat: "悬浮",
    dockFloatDescription: "圆角悬浮卡片，离屏幕底边更远",
    dockBar: "贴边",
    dockBarDescription: "贴住屏幕底部，占用更少高度",
    dockSize: "按钮大小",
    dockSizeDescription: "按住按钮的高度，按你的拇指调节。",
    dockCollapse: "收起按钮区",
    dockExpand: "展开按钮区",
    rowTypography: "横向模式排版",
    rowTypographyDescription: "微调横向并排时的字号、行距与间距，适配你的手机屏幕。",
    fontScale: "字号",
    lineScale: "行距",
    gapScale: "间距",
    resetTypography: "恢复默认",
    suggestionFontSize: "建议字号",
    suggestionFontSizeDescription: "调整回复建议的字号，方便在不同屏幕上阅读。",
    showDetail: "展开要点",
    hideDetail: "收起",
    altPhrasing: "替代说法",
    keyPoints: "词汇要点",
    holdMe: "按住：我说",
    holdOther: "按住：对方说",
    holdHint: "对方说话时按住，松手即结束这句话。",
    holdingMe: "录音中·我",
    releaseToSend: "松开即结束这句并发送",
    holdingOther: "录音中·对方",
    askIdeas: "给我思路",
    features: "功能",
    featuresDescription: "控制会话中的辅助行为。",
    autoSuggest: "自动出思路",
    autoSuggestDescription: "对方说完一句后自动生成三条回复；关掉后只靠「给我思路」。",
    showStallingTip: "拖延小技巧",
    showStallingTipDescription: "等待思路时显示可用来缓冲的短句。",
    hapticsEnabled: "触感反馈",
    hapticsEnabledDescription: "按住说话和按钮点击时震动。",
    showVadDiagnostics: "语音诊断面板",
    showVadDiagnosticsDescription: "显示音量、静音切句等调试信息（开发用）。",
    display: "显示与布局",
    screenPermissionNotNeeded: "仅用麦克风时不需要",
    screenPermissionUnsupported: "当前浏览器不支持系统音频",
    screenPermissionOnStart: "开始会话并选择系统音频时会弹出授权",
    permissions: "权限",
    microphonePermission: "麦克风权限",
    screenPermission: "系统音频 / 屏幕录制权限",
    granted: "已允许",
    needsPermission: "需要允许",
    requestPermission: "请求权限",
    openSystemSettings: "打开系统设置",
    personalization: "个性化",
    useProfileContext: "参考我的资料",
    useProfileContextDescription: "让教练根据你的身份、场景和语气来给思路。",
    useMemoryContext: "参考我的记忆",
    useMemoryContextDescription: "生成思路时引用你保存的长期记忆条目。",
    manageMemory: "管理资料与记忆",
    openMemory: "打开",
    exportData: "导出会话记录",
    exportDataDescription: "把本机的会话转写与总结下载为 JSON 文件。",
    exportAction: "导出",
    nothingToExport: "还没有可导出的会话记录",
    exported: "已导出",
    accountSecurity: "账号与安全",
    signedInAs: "当前账号",
    notSignedIn: "未登录",
    changePassword: "修改密码",
    changePasswordDescription: "输入新密码后立即生效，下次登录请使用新密码。",
    newPassword: "新密码",
    save: "保存",
    passwordTooShort: "密码至少 6 位",
    passwordUpdated: "密码已更新",
    signOutAll: "登出所有设备",
    signOutAllDescription: "结束所有设备上的登录状态，包括这台设备。",
    signOutAllAction: "全部登出",
    dataPrivacy: "数据与隐私",
    clearHistory: "清除历史记录",
    clearHistoryTitle: "清除全部历史记录？",
    clearHistoryDescription: "已停止的会话、转写、建议与总结将从本机和云端永久删除。",
    deleteSession: "删除这条记录",
    deleteSessionTitle: "删除这条会话记录？",
    deleteSessionDescription: "该会话的转写、建议与总结将被永久删除，无法恢复。",
    resetPersonalData: "清除个人数据并重置",
    resetTitle: "清除个人数据并重置？",
    resetDescription: "会删除偏好和历史（含云端会话），但保留已经准备好的本机语音能力。",
    about: "关于",
    version: "版本",
    lockedWhileActive: "进行中或暂停的会话会锁定会话设置。停止后即可修改。",
    currentSession: "本次会话",
    noHistory: "还没有已保存的会话",
    summaryPending: "正在整理本次会话…",
    summaryFailed: "整理失败",
    retry: "重试",
    syncPending: "待同步",
    activeSessionRecovered: "上次会话意外中断，已恢复为暂停状态。",
    selectLanguage: "选择对话语言",
    onboardingDescription: "确认双方使用的语言和你的当前水平。",
    continueSetup: "确认并继续",
    languageJapanese: "日语",
    languageEnglish: "英语",
    languageChinese: "中文",
    levelBeginner: "初级",
    levelIntermediate: "中级",
    levelAdvanced: "高级",
    more: "更多操作",
    showWindow: "显示悬浮窗",
    hideWindow: "隐藏悬浮窗",
    moveWindow: "移动悬浮窗",
    processing: "处理中…",
    errorPrefix: "错误：",
    sessionSummary: "会话总结",
    sessionDetails: "会话详情",

    sessionUnavailable: "语音暂时不可用，请检查权限或音频设置后重试。",
    selectNetworkNode: "选择本次会话的网络节点",
    networkNodeDescription:
      "以下延迟为你的设备到节点的实测往返时间。选择后，本次会话中不会切换节点。",
    checkingLatency: "正在测量节点延迟…",
    localNode: "本地节点",
    japanNode: "日本主节点",
    relayNode: "中转节点",
    encryptedConnection: "HTTPS 加密连接",
    insecureRelayWarning:
      "HTTP 未加密：语音、提示词、回复和短令牌可能被链路中间方看到或篡改。选择即表示你了解此风险。",
    nodeUnreachable: "当前不可达",
    nodeProbeFailed: "节点测速失败",
    refreshLatency: "重新测速",
    defaultNode: "设置默认",
    defaultNetworkNode: "默认网络节点",
    defaultNetworkNodeDescription: "停止会话后可修改；下一次会话开始时仍会显示最新延迟并请你确认。",
  },
  ja: {
    appName: "KiboTalk",
    conversation: "会話",
    suggestions: "返信候補",
    conversationHistory: "会話ログ",
    history: "履歴",
    settings: "設定",
    close: "閉じる",
    back: "戻る",
    start: "新しい会話を開始",
    pause: "一時停止",
    resume: "再開",
    stop: "停止",
    stopAndSave: "停止して保存",
    cancel: "キャンセル",
    confirm: "確認",
    listening: "文字起こし中",
    paused: "一時停止中",
    stopped: "停止済み",
    preparing: "音声機能を準備中…",
    preparationFailed: "音声機能を準備できませんでした",
    emptySuggestions: "「開始」を押すと、すぐ口に出せる返信が3つここに出ます",
    generatingSuggestions: "返信候補を作成中…",
    aiConnecting: "モデルに接続中…",
    aiRetrying: "同じ文脈で再生成中…",
    aiAttempt: "リトライ {n} 回目",
    aiStreaming: "ストリーミング生成中…",
    aiDone: "生成完了",
    aiFailed: "生成に失敗しました",
    aiRetry: "再試行",
    previousRound: "前のターン",
    noTranscript: "会話はまだありません",
    me: "自分",
    other: "相手",
    sttFailed: "この部分の文字起こしに失敗しました",
    aiSuggestions: "AI 候補",
    stopTitle: "この会話を停止して保存しますか？",
    stopDescription: "文字起こしと候補を保存します。次に開始すると新しい会話になります。",
    quit: "KiboTalk を終了",
    quitTitleActive: "会話を終了してアプリを終了しますか？",
    quitTitleStopped: "KiboTalk を終了しますか？",
    quitDescriptionActive: "会話を保存してから KiboTalk を終了します。",
    quitDescriptionStopped: "フローティングウィンドウとメニューバーアイコンを閉じます。",
    general: "一般",
    uiLanguage: "表示言語",
    uiLanguageDescription: "会話停止中のみ変更できます。すぐに反映されます。",
    theme: "外観",
    system: "システム",
    light: "ライト",
    dark: "ダーク",
    launchAtLogin: "ログイン時に起動",
    conversationSettings: "会話",
    conversationLanguage: "会話言語",
    level: "現在のレベル",
    audioSource: "音声ソース",
    microphone: "マイク",
    systemAudio: "システム音声",
    bothAudio: "両方",
    microphoneDescription: "対面会話、身近な話",
    systemAudioDescription: "オンライン通話・動画音声",
    bothAudioDescription: "自分と相手の声を同時に収録",
    microphoneDevice: "マイクデバイス",
    systemDefault: "システム既定",
    headphonesHint: "同時収録では、スピーカーの回り込みを防ぐためヘッドホンを推奨します。",
    captureMode: "入力モード",
    captureModeDescription: "発話の区切りをどう決めるかを選びます。",
    pushMode: "押している間だけ録音",
    pushModeDescription: "話している間ボタンを押し、離すと候補の生成が始まります。",
    continuousMode: "常時聞き取り",
    continuousModeDescription: "ずっと文字起こし。設定で「自動で候補」を切り替えできます。",
    panelLayout: "パネルの並び",
    panelLayoutDescription: "会話と返答候補の並べ方を選びます。",
    layoutAuto: "自動",
    layoutAutoDescription: "PCは左右、スマホは上下",
    layoutRow: "横並び",
    layoutRowDescription: "常に左右に並べて表示",
    layoutColumn: "縦並び",
    layoutColumnDescription: "常に上下に並べ、高さを制限",
    scrollSync: "スクロール",
    scrollSyncDescription: "左右のパネルを連動させるか選びます。",
    scrollLinked: "連動",
    scrollLinkedDescription: "片方を動かすともう片方も比例して動く",
    scrollIndependent: "独立",
    scrollIndependentDescription: "それぞれ別々にスクロール",
    mobileDock: "スマホの操作バー",
    mobileDockDescription: "下部の「押して話す」エリアを調整し、上の内容を隠さないようにします。",
    dockFloat: "フローティング",
    dockFloatDescription: "角丸のカード。画面下端から少し浮きます",
    dockBar: "下端固定",
    dockBarDescription: "画面下端に密着し、高さを節約します",
    dockSize: "ボタンの大きさ",
    dockSizeDescription: "押して話すボタンの高さを親指に合わせて調整します。",
    dockCollapse: "操作バーを畳む",
    dockExpand: "操作バーを開く",
    rowTypography: "横並びの文字設定",
    rowTypographyDescription: "横並び時の文字サイズ・行間・余白を端末に合わせて微調整します。",
    fontScale: "文字サイズ",
    lineScale: "行間",
    gapScale: "余白",
    resetTypography: "初期値に戻す",
    suggestionFontSize: "返信候補の文字サイズ",
    suggestionFontSizeDescription: "返信候補の文字サイズを画面に合わせて調整します。",
    showDetail: "詳細を開く",
    hideDetail: "閉じる",
    altPhrasing: "言い換え",
    keyPoints: "語句メモ",
    holdMe: "長押し：自分",
    holdOther: "長押し：相手",
    holdHint: "話している間は長押し、離すと1文が確定します。",
    holdingMe: "録音中・自分",
    releaseToSend: "指を離すと確定して送信します",
    holdingOther: "録音中・相手",
    askIdeas: "候補を出す",
    features: "機能",
    featuresDescription: "セッション中の補助動作を切り替えます。",
    autoSuggest: "自動で候補",
    autoSuggestDescription: "相手の発話後に3つの返信候補を自動生成。オフなら「候補を出す」のみ。",
    showStallingTip: "つなぎフレーズ",
    showStallingTipDescription: "候補待ちのあいだ、つなぎに使える短い文を表示します。",
    hapticsEnabled: "触覚フィードバック",
    hapticsEnabledDescription: "長押し録音やボタン操作で振動します。",
    showVadDiagnostics: "音声診断パネル",
    showVadDiagnosticsDescription: "音量・無音区切りなどのデバッグ情報を表示（開発用）。",
    display: "表示とレイアウト",
    screenPermissionNotNeeded: "マイクのみなら不要",
    screenPermissionUnsupported: "このブラウザはシステム音声に非対応",
    screenPermissionOnStart: "セッション開始時にシステム音声を選ぶと許諾が出ます",
    permissions: "権限",
    microphonePermission: "マイク権限",
    screenPermission: "システム音声 / 画面収録権限",
    granted: "許可済み",
    needsPermission: "許可が必要",
    requestPermission: "権限をリクエスト",
    openSystemSettings: "システム設定を開く",
    personalization: "パーソナライズ",
    useProfileContext: "プロフィールを参照",
    useProfileContextDescription: "あなたの立場・場面・トーンを踏まえて提案します。",
    useMemoryContext: "メモリーを参照",
    useMemoryContextDescription: "保存した長期メモリーを提案に反映します。",
    manageMemory: "プロフィールとメモリー",
    openMemory: "開く",
    exportData: "会話記録を書き出す",
    exportDataDescription: "この端末の文字起こしとまとめを JSON で保存します。",
    exportAction: "書き出す",
    nothingToExport: "書き出せる記録がありません",
    exported: "書き出しました",
    accountSecurity: "アカウントとセキュリティ",
    signedInAs: "ログイン中",
    notSignedIn: "未ログイン",
    changePassword: "パスワードを変更",
    changePasswordDescription: "新しいパスワードはすぐに有効になります。",
    newPassword: "新しいパスワード",
    save: "保存",
    passwordTooShort: "パスワードは6文字以上",
    passwordUpdated: "パスワードを更新しました",
    signOutAll: "すべての端末からログアウト",
    signOutAllDescription: "この端末を含むすべてのセッションを終了します。",
    signOutAllAction: "ログアウト",
    dataPrivacy: "データとプライバシー",
    clearHistory: "履歴を消去",
    clearHistoryTitle: "すべての履歴を消去しますか？",
    clearHistoryDescription:
      "停止済みの会話、文字起こし、候補、まとめをこの端末とクラウドから削除します。",
    deleteSession: "この記録を削除",
    deleteSessionTitle: "この会話記録を削除しますか？",
    deleteSessionDescription:
      "この会話の文字起こし・候補・まとめが完全に削除され、元に戻せません。",
    resetPersonalData: "個人データを消去してリセット",
    resetTitle: "個人データを消去してリセットしますか？",
    resetDescription:
      "設定と履歴（クラウドの会話含む）を削除します。準備済みの音声機能は残ります。",
    about: "このアプリについて",
    version: "バージョン",
    lockedWhileActive: "進行中または一時停止中は会話設定を変更できません。停止後に変更できます。",
    currentSession: "今回の会話",
    noHistory: "保存された会話はまだありません",
    summaryPending: "会話を整理しています…",
    summaryFailed: "整理に失敗しました",
    retry: "再試行",
    syncPending: "同期待ち",
    activeSessionRecovered: "前回の会話が中断されたため、一時停止状態で復元しました。",
    selectLanguage: "会話言語を選択",
    onboardingDescription: "二人が使う言語と、あなたの現在のレベルを選んでください。",
    continueSetup: "確認して続ける",
    languageJapanese: "日本語",
    languageEnglish: "英語",
    languageChinese: "中国語",
    levelBeginner: "初級",
    levelIntermediate: "中級",
    levelAdvanced: "上級",
    more: "その他",
    showWindow: "ウィンドウを表示",
    hideWindow: "ウィンドウを隠す",
    moveWindow: "ウィンドウを移動",
    processing: "処理中…",
    errorPrefix: "エラー：",
    sessionSummary: "会話のまとめ",
    sessionDetails: "会話の詳細",

    sessionUnavailable:
      "音声を利用できません。権限または音声設定を確認して、もう一度お試しください。",
    selectNetworkNode: "このセッションのネットワークノードを選択",
    networkNodeDescription:
      "表示される遅延は、この端末から各ノードまでの実測往復時間です。セッション中はノードを切り替えません。",
    checkingLatency: "ノードの遅延を測定しています…",
    localNode: "ローカルノード",
    japanNode: "日本メインノード",
    relayNode: "リレーノード",
    encryptedConnection: "HTTPS 暗号化接続",
    insecureRelayWarning:
      "HTTP は暗号化されません。音声、プロンプト、返信、短期トークンを経路上の第三者が閲覧または改ざんする可能性があります。選択すると、このリスクを理解したものとみなされます。",
    nodeUnreachable: "現在接続できません",
    nodeProbeFailed: "ノードの測定に失敗しました",
    refreshLatency: "再測定",
    defaultNode: "設定の既定",
    defaultNetworkNode: "既定のネットワークノード",
    defaultNetworkNodeDescription:
      "会話停止中に変更できます。次の開始時にも最新の遅延を表示して確認します。",
  },
  en: {
    appName: "KiboTalk",
    conversation: "Conversation",
    suggestions: "Reply suggestions",
    conversationHistory: "Transcript",
    history: "History",
    settings: "Settings",
    close: "Close",
    back: "Back",
    start: "Start new session",
    pause: "Pause",
    resume: "Resume",
    stop: "Stop",
    stopAndSave: "Stop and save",
    cancel: "Cancel",
    confirm: "Confirm",
    listening: "Transcribing",
    paused: "Paused",
    stopped: "Stopped",
    preparing: "Preparing speech features…",
    preparationFailed: "Could not prepare speech features",
    emptySuggestions: "Start below — three ready-to-say replies will land here",
    generatingSuggestions: "Generating suggestions…",
    aiConnecting: "Connecting to the model…",
    aiRetrying: "Retrying with the same context…",
    aiAttempt: "Attempt {n}",
    aiStreaming: "Streaming response…",
    aiDone: "Response complete",
    aiFailed: "Generation failed",
    aiRetry: "Retry",
    previousRound: "Previous turn",
    noTranscript: "No conversation yet",
    me: "Me",
    other: "Other",
    sttFailed: "Transcription failed for this segment",
    aiSuggestions: "AI suggestions",
    stopTitle: "Stop and save this session?",
    stopDescription:
      "The transcript and suggestions will be saved now. Starting again creates a new conversation.",
    quit: "Quit KiboTalk",
    quitTitleActive: "End the session and quit?",
    quitTitleStopped: "Quit KiboTalk?",
    quitDescriptionActive: "The session will be sealed and saved before KiboTalk quits.",
    quitDescriptionStopped: "The floating window and menu bar icon will close.",
    general: "General",
    uiLanguage: "Interface language",
    uiLanguageDescription: "Change it only while stopped. The interface updates immediately.",
    theme: "Appearance",
    system: "System",
    light: "Light",
    dark: "Dark",
    launchAtLogin: "Launch at login",
    conversationSettings: "Conversation",
    conversationLanguage: "Conversation language",
    level: "Current level",
    audioSource: "Audio source",
    microphone: "Microphone",
    systemAudio: "System audio",
    bothAudio: "Both",
    microphoneDescription: "In-person conversation",
    systemAudioDescription: "Online calls or media audio",
    bothAudioDescription: "Capture both sides at once",
    microphoneDevice: "Microphone device",
    systemDefault: "System default",
    headphonesHint: "Use headphones when capturing both sources to prevent speaker echo.",
    captureMode: "Input mode",
    captureModeDescription: "Choose how the app knows a turn is finished.",
    pushMode: "Hold to talk",
    pushModeDescription: "Hold a button while someone speaks; ideas start when you release.",
    continuousMode: "Always listening",
    continuousModeDescription: "Keeps transcribing; turn auto-suggest on or off in Settings.",
    panelLayout: "Panel layout",
    panelLayoutDescription: "Choose how the conversation and suggestions are arranged.",
    layoutAuto: "Auto",
    layoutAutoDescription: "Side by side on desktop, stacked on phone",
    layoutRow: "Side by side",
    layoutRowDescription: "Always show both panels in two columns",
    layoutColumn: "Stacked",
    layoutColumnDescription: "Always stack them, both height-capped",
    scrollSync: "Scrolling",
    scrollSyncDescription: "Choose whether the two side panels follow each other.",
    scrollLinked: "Linked",
    scrollLinkedDescription: "Scrolling one panel moves the other proportionally",
    scrollIndependent: "Independent",
    scrollIndependentDescription: "Each panel scrolls on its own, never interrupting",
    mobileDock: "Phone talk dock",
    mobileDockDescription: "Tune the bottom hold-to-talk area so it never covers what you read.",
    dockFloat: "Floating",
    dockFloatDescription: "Rounded card lifted off the bottom edge",
    dockBar: "Edge bar",
    dockBarDescription: "Anchored to the bottom edge, takes less height",
    dockSize: "Button size",
    dockSizeDescription: "Height of the hold-to-talk buttons, sized for your thumb.",
    dockCollapse: "Collapse dock",
    dockExpand: "Expand dock",
    rowTypography: "Side-by-side typography",
    rowTypographyDescription:
      "Fine-tune font size, line height and spacing for the row layout on your screen.",
    fontScale: "Font size",
    lineScale: "Line height",
    gapScale: "Spacing",
    resetTypography: "Reset",
    suggestionFontSize: "Suggestion font size",
    suggestionFontSizeDescription: "Adjust the size of reply suggestions to fit your screen.",
    showDetail: "Show details",
    hideDetail: "Hide",
    altPhrasing: "Alternative phrasing",
    keyPoints: "Key words",
    holdMe: "Hold: me",
    holdOther: "Hold: other",
    holdHint: "Hold while the person speaks, release to finish the sentence.",
    holdingMe: "Recording · me",
    releaseToSend: "Release to finish and send this line",
    holdingOther: "Recording · other",
    askIdeas: "Give me ideas",
    features: "Features",
    featuresDescription: "Control helpers during a conversation.",
    autoSuggest: "Auto-suggest",
    autoSuggestDescription:
      "Generate three replies after the other person finishes; off means tap “Give me ideas” only.",
    showStallingTip: "Stalling tip",
    showStallingTipDescription: "While waiting for ideas, show a short buffer phrase you can use.",
    hapticsEnabled: "Haptics",
    hapticsEnabledDescription: "Vibrate on hold-to-talk and button taps.",
    showVadDiagnostics: "Voice diagnostics",
    showVadDiagnosticsDescription: "Show volume / silence-cut debug info (for development).",
    display: "Display & layout",
    screenPermissionNotNeeded: "Not needed for mic-only",
    screenPermissionUnsupported: "System audio not supported in this browser",
    screenPermissionOnStart: "Prompted when you start a session and pick system audio",
    permissions: "Permissions",
    microphonePermission: "Microphone permission",
    screenPermission: "System audio / screen recording permission",
    granted: "Allowed",
    needsPermission: "Permission needed",
    requestPermission: "Request permission",
    openSystemSettings: "Open system settings",
    personalization: "Personalization",
    useProfileContext: "Use my profile",
    useProfileContextDescription:
      "Let the coach use your role, scenes, and tone when suggesting replies.",
    useMemoryContext: "Use my memories",
    useMemoryContextDescription: "Reference your saved long-term memories when generating ideas.",
    manageMemory: "Profile & memories",
    openMemory: "Open",
    exportData: "Export sessions",
    exportDataDescription: "Download this device's transcripts and summaries as JSON.",
    exportAction: "Export",
    nothingToExport: "No sessions to export yet",
    exported: "Exported",
    accountSecurity: "Account & security",
    signedInAs: "Signed in as",
    notSignedIn: "Not signed in",
    changePassword: "Change password",
    changePasswordDescription: "The new password takes effect immediately.",
    newPassword: "New password",
    save: "Save",
    passwordTooShort: "Password must be at least 6 characters",
    passwordUpdated: "Password updated",
    signOutAll: "Sign out everywhere",
    signOutAllDescription: "End sessions on all devices, including this one.",
    signOutAllAction: "Sign out",
    dataPrivacy: "Data & privacy",
    clearHistory: "Clear history",
    clearHistoryTitle: "Clear all history?",
    clearHistoryDescription:
      "Stopped sessions, transcripts, suggestions, and summaries will be deleted from this device and the cloud.",
    deleteSession: "Delete this session",
    deleteSessionTitle: "Delete this session?",
    deleteSessionDescription:
      "This session's transcript, suggestions, and summary will be permanently deleted.",
    resetPersonalData: "Clear personal data and reset",
    resetTitle: "Clear personal data and reset?",
    resetDescription:
      "Preferences and history (including cloud sessions) are deleted. Prepared speech features remain.",
    about: "About",
    version: "Version",
    lockedWhileActive:
      "Conversation settings are locked while running or paused. Stop the session to change them.",
    currentSession: "Current session",
    noHistory: "No saved sessions yet",
    summaryPending: "Organizing this session…",
    summaryFailed: "Could not organize this session",
    retry: "Retry",
    syncPending: "Sync pending",
    activeSessionRecovered: "The previous session was interrupted and restored as paused.",
    selectLanguage: "Choose conversation language",
    onboardingDescription: "Confirm the language both people will use and your current level.",
    continueSetup: "Confirm and continue",
    languageJapanese: "Japanese",
    languageEnglish: "English",
    languageChinese: "Chinese",
    levelBeginner: "Beginner",
    levelIntermediate: "Intermediate",
    levelAdvanced: "Advanced",
    more: "More actions",
    showWindow: "Show floating window",
    hideWindow: "Hide floating window",
    moveWindow: "Move floating window",
    processing: "Processing…",
    errorPrefix: "Error:",
    sessionSummary: "Session summary",
    sessionDetails: "Session details",

    sessionUnavailable: "Speech is unavailable. Check permissions or audio settings and try again.",
    selectNetworkNode: "Choose a network node for this session",
    networkNodeDescription:
      "Latency is the measured round trip from this device to each node. The node will not change during the session.",
    checkingLatency: "Measuring node latency…",
    localNode: "Local node",
    japanNode: "Japan primary",
    relayNode: "Relay node",
    encryptedConnection: "Encrypted with HTTPS",
    insecureRelayWarning:
      "HTTP is not encrypted. An intermediary may read or alter audio, prompts, replies, and the short-lived token. Selecting it confirms you understand this risk.",
    nodeUnreachable: "Currently unreachable",
    nodeProbeFailed: "Could not measure node latency",
    refreshLatency: "Measure again",
    defaultNode: "Settings default",
    defaultNetworkNode: "Default network node",
    defaultNetworkNodeDescription:
      "Change it while stopped. The next session still shows fresh latency and asks for confirmation.",
  },
} as const;

export type UiLang = keyof typeof dict;
export type TKey = keyof (typeof dict)["en"];
